repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
    -   id: flake8
        args:  # arguments to configure flake8
            -   --max-line-length=120
            -   --exclude=env,venv
            -   --ignore=BLK100
        additional_dependencies:
            -   flake8-bugbear
            -   flake8-eradicate
            -   pep8-naming
            -   flake8-black
